title: ReaDDy documentation
email: readdyadmin@lists.fu-berlin.de
description: >
  Documentation of ReaDDy, the particle-based reaction-diffusion simulator
baseurl:
url: https://readdy.github.io
github_username: readdy
sass:
  sass_dir: _sass
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
collections:
  home:
    output: false
  system:
    output: false
  simulation:
    output: false
  results:
    output: false
  development:
    output: false
  demonstration:
    output: true
    permalink: /:collection/:path
  validation:
    output: true
    permalink: /:collection/:path
  benchmark:
    output: true
    permalink: /:collection/:path
defaults:
  - scope:
      path: ""
      type: "demonstration"
    values:
      layout: "notebook"
      title: "defaulttitle"
  - scope:
      path: ""
      type: "validation"
    values:
      layout: "notebook"
      title: "defaulttitle"
  - scope:
      path: ""
      type: "benchmark"
    values:
      layout: "notebook"
      title: "defaulttitle"
